kind: pipeline
name: default

steps:
  - name: composer
    image: composer
    commands:
      - composer install --ignore-platform-reqs
      - composer bin codestyle install --ignore-platform-reqs
      - composer bin phpstan install --ignore-platform-reqs
      - composer bin phpunit install --ignore-platform-reqs
      - composer bin phan install --ignore-platform-reqs

  - name: codestyle
    image: php:7.3-cli
    commands:
      - make style

  - name: static-code-analysis
    image: php:7.3-cli
    commands:
      - make phpstan

  - name: static-code-analysis-phan
    image: php:7.3-cli
    commands:
      - pecl install ast
      - docker-php-ext-enable ast
      - make phan

  - name: unit-tests
    image: php:7.3-cli
    commands:
      - make unit

  - name: functional-tests
    image: php:7.3-cli
    commands:
      - make functional

  - name: server
    image: php:7.3-cli
    detach: true
    environment:
      JWK_JSON: '{"kid":"nHb9SPdujpSiWqUZ95T_bHRQ_tghQokyXS4RTo5_daI","use":"sig","kty":"EC","crv":"P-256","x":"xcxqm_RqIt3LsBGtggB7AtIzmKufs2KAS_KkVUueAjM","y":"YA3ZyMM6F10BvF9Q6pm4zd_cwFCuwVFQo7Vddi97JA4","d":"-h7ESUbdNZa5kpO9Ox2C95akpjzUNGfQmFgs2WA2GsY"}'
      KEYSERVICE_DIR: '%kernel.project_dir%/tests/data/signing-keys'
      WORKSPACE: '%kernel.cache_dir%'
    commands:
      - cd public
      - php -S 0.0.0.0:8000

  - name: acceptance
    image: php:7.3-cli
    environment:
      JWK_JSON: '{"kid":"nHb9SPdujpSiWqUZ95T_bHRQ_tghQokyXS4RTo5_daI","use":"sig","kty":"EC","crv":"P-256","x":"xcxqm_RqIt3LsBGtggB7AtIzmKufs2KAS_KkVUueAjM","y":"YA3ZyMM6F10BvF9Q6pm4zd_cwFCuwVFQo7Vddi97JA4","d":"-h7ESUbdNZa5kpO9Ox2C95akpjzUNGfQmFgs2WA2GsY"}'
    commands:
      - bash ./tests/acceptance/basic-test.sh server:8000