kind: pipeline
name: default

steps:
  - name: composer
    image: composer
    commands:
      - composer install --ignore-platform-reqs
      - composer bin codestyle install --ignore-platform-reqs
      - composer bin phpstan install --ignore-platform-reqs
      - composer bin phpunit install --ignore-platform-reqs
      - composer bin phan install --ignore-platform-reqs

  - name: codestyle
    image: php:7.3-cli
    commands:
      - make style

  - name: static-code-analysis
    image: php:7.3-cli
    commands:
      - make phpstan

  - name: static-code-analysis-phan
    image: php:7.3-cli
    commands:
      - pecl install ast
      - docker-php-ext-enable ast
      - make phan

  - name: unit-tests
    image: php:7.3-cli
    commands:
      - make unit

  - name: functional-tests
    image: php:7.3-cli
    commands:
      - make functional

  - name: server-local-keyservice
    image: php:7.3-cli
    detach: true
    commands:
      - cd public
      - APP_ENV=local php -S 0.0.0.0:8000

  - name: acceptance
    image: php:7.3-cli
    environment:
      APP_ENV: local
    commands:
      - bash ./tests/acceptance/basic-test.sh server-local-keyservice:8000