version: '3.6'

services:
  vault:
    image: vault
    ports:
      - "127.0.0.1:8200:8200"
    volumes:
      - ./tests/vault/file:/drone/src/tests/vault/file:rw
      - ./tests/vault/config:/drone/src/tests/vault/config:rw
    entrypoint: vault server -config=/drone/src/tests/vault/config/vault.json